
(function(){'use strict';
function fa4(){return typeof LANG==='undefined'||LANG==='fa'}
function tx4(a,b){return fa4()?a:b}
function esc4(x){var d=document.createElement('div');d.textContent=String(x==null?'':x);return d.innerHTML}
function fnLiveRequestExit(){var message=tx4('آیا مطمئنید می‌خواهید پخش متوقف و از بخش Live خارج شوید؟','Are you sure you want to stop playback and leave Live TV?');if(window.confirm(message)){if(window.fnLiveClosePlayer)window.fnLiveClosePlayer();if(typeof switchTab==='function')switchTab('home')}}
window.fnLiveRequestExit=fnLiveRequestExit;
window.addEventListener('popstate',function(e){if(document.body.classList.contains('fn-live-mode')){e.preventDefault();try{history.pushState({page:'live'},'',location.href)}catch(x){}fnLiveRequestExit()}},true);
window.fnLiveResetFilters=function(){var search=document.getElementById('fn-live-search');if(typeof fnLiveClearFailed==='function')fnLiveClearFailed();if(search)search.value='';['fn-live-topic','fn-live-country','fn-live-language','fn-live-sort'].forEach(function(id){var e=document.getElementById(id);if(e){e.value=(id==='fn-live-sort'?'name':'all');e.dispatchEvent(new Event('change',{bubbles:true}));}});document.querySelectorAll('.fn-live-filter-custom.open').forEach(function(x){x.classList.remove('open')});if(typeof fnLiveApply==='function')fnLiveApply();}
function setupHeader(){var live=document.getElementById('live-tab'),h=live&&live.querySelector('header'),a=h&&h.querySelector('.fn-live-top-actions');if(!a)return;a.innerHTML='<button class="fn-live-icon-btn" onclick="fnLiveRequestExit()" title="'+tx4('بازگشت','Back')+'" aria-label="'+tx4('بازگشت','Back')+'"><i class="fa-solid fa-arrow-right"></i></button><button class="fn-live-icon-btn" onclick="fnLiveAppFullscreen()" title="'+tx4('تمام‌صفحهٔ اپ','Fullscreen app')+'" aria-label="'+tx4('تمام‌صفحهٔ اپ','Fullscreen app')+'"><i class="fa-solid fa-expand"></i></button><button id="fn-live-fav-toggle" class="fn-live-icon-btn" onclick="fnLiveToggleFavorites()" title="'+tx4('علاقه‌مندی‌ها','Favorites')+'" aria-label="'+tx4('علاقه‌مندی‌ها','Favorites')+'"><i class="fa-solid fa-star"></i></button><button class="fn-live-icon-btn" onclick="fnLiveResetFilters()" title="'+tx4('بازنشانی فیلترها','Reset filters')+'" aria-label="'+tx4('بازنشانی فیلترها','Reset filters')+'"><i class="fa-solid fa-rotate-right"></i></button><button class="fn-live-icon-btn" onclick="fnLiveRequestExit()" title="'+tx4('بستن','Close')+'" aria-label="'+tx4('بستن','Close')+'"><i class="fa-solid fa-xmark"></i></button>';var ht=document.getElementById('fn-live-title-text'),hs=document.getElementById('fn-live-subtitle');if(ht)ht.textContent=tx4('پخش زنده','LIVE TV');if(hs)hs.textContent=tx4('پخش زنده','LIVE TV');document.querySelectorAll('#live-tab .fn-live-filter-field>label').forEach(function(x){x.textContent=tx4(x.getAttribute('data-fa')||'',x.getAttribute('data-en')||'')});h.setAttribute('data-v4','1')}
function setupPlayer(){var bar=document.querySelector('#fn-live-player .fn-live-player-bar');if(!bar||bar.getAttribute('data-v4'))return;bar.setAttribute('data-v4','1');bar.innerHTML='<button class="fn-live-nav-btn" onclick="fnLivePrev()" title="'+tx4('شبکهٔ قبلی','Previous channel')+'" aria-label="'+tx4('شبکهٔ قبلی','Previous channel')+'"><i class="fa-solid fa-backward-step"></i></button><button id="fn-live-pause" class="fn-live-nav-btn" onclick="fnLivePauseToggle()" title="'+tx4('مکث','Pause')+'" aria-label="'+tx4('مکث','Pause')+'"><i class="fa-solid fa-pause"></i></button><button class="fn-live-nav-btn" onclick="fnLiveNext()" title="'+tx4('شبکهٔ بعدی','Next channel')+'" aria-label="'+tx4('شبکهٔ بعدی','Next channel')+'"><i class="fa-solid fa-forward-step"></i></button><button class="fn-live-close" onclick="fnLiveClosePlayer()" title="'+tx4('بستن پلیر','Close player')+'" aria-label="'+tx4('بستن پلیر','Close player')+'"><i class="fa-solid fa-xmark"></i></button><div id="fn-live-now" class="fn-live-now"></div><span id="fn-live-state" class="fn-live-state"></span>'}
function setupCountrySearch(){document.querySelectorAll('.fn-live-filter-custom').forEach(function(w){if(w.querySelector('.fn-live-filter-search'))return;var menu=w.querySelector('.fn-live-filter-menu');if(!menu)return;var input=document.createElement('input');input.className='fn-live-filter-search';input.type='search';var isLang=!!w.querySelector('#fn-live-language');input.placeholder=isLang?tx4('جستجوی زبان…','Search languages…'):tx4('جستجوی کشور…','Search countries…');input.setAttribute('aria-label',input.placeholder);menu.querySelectorAll('.fn-live-filter-option').forEach(function(o){if(o.querySelector('.fn-lang-flag')&&((o.textContent||'').indexOf('🌐')>=0||/All countries|همه کشورها|All languages|همه زبان‌ها/.test(o.textContent||'')))o.setAttribute('data-all','1');var t=o.textContent||'';t=t.replace(/^[^\p{L}\p{N}]*/u,'').replace(/(^|\s)[A-Z]{2}\s*[—-]?\s*/g,' ').trim();o.setAttribute('data-search',t)});input.oninput=function(){var q=String(input.value||'').trim().toLocaleLowerCase();menu.querySelectorAll('.fn-live-filter-option').forEach(function(o){if(o.getAttribute('data-all')==='1'){o.classList.remove('is-filtered');return}var text=(o.getAttribute('data-search')||o.textContent||'').toLocaleLowerCase();o.classList.toggle('is-filtered',!!q&&!text.startsWith(q))})};menu.insertBefore(input,menu.firstChild);var oldOpen=w.querySelector('button');if(oldOpen)oldOpen.addEventListener('click',function(){setTimeout(function(){input.focus()},20)})})}
function stripCountryCode(){document.querySelectorAll('.fn-live-filter-option span:last-child').forEach(function(t){t.textContent=t.textContent.replace(/(^|\s)[A-Z]{2}\s*[—-]?\s*/g,' ').trim()})}
function rebuildFilterLabels(){setupHeader();setupPlayer();document.querySelectorAll('.fn-live-filter-custom').forEach(function(w){var b=w.querySelector('button.fn-live-select'),s=w.previousElementSibling;if(b&&s&&s.options){var o=s.options[s.selectedIndex],isCountry=s.id==='fn-live-country',flag=isCountry&&o&&o.value&&o.value!=='all'&&typeof countryFlag==='function'?countryFlag(o.value):'';b.innerHTML=(flag?'<span class="fn-lang-flag"><img src="'+esc4(flag)+'" alt=""></span>':'')+'<span>'+esc4(o?o.textContent:'')+'</span>'}});setupCountrySearch();stripCountryCode()}
window.fnLiveAppFullscreen=function(){var root=document.documentElement;if(document.fullscreenElement)document.exitFullscreen();else if(root.requestFullscreen)root.requestFullscreen().catch(function(){})}
window.fnLivePauseToggle=function(){var v=document.getElementById('fn-live-video'),b=document.getElementById('fn-live-pause');if(!v)return;if(v.paused){v.play().catch(function(){});if(b){b.innerHTML='<i class="fa-solid fa-pause"></i>';b.title=tx4('مکث','Pause')}}else{v.pause();if(b){b.innerHTML='<i class="fa-solid fa-play"></i>';b.title=tx4('پخش','Play')}}}
var oldPlay=window.fnLiveRetry;document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('.fn-live-card'))setTimeout(function(){var b=document.getElementById('fn-live-pause');if(b){b.innerHTML='<i class="fa-solid fa-pause"></i>';b.title=tx4('مکث','Pause')}},80)},true)
var last='';setInterval(function(){var now=String(typeof LANG==='undefined'?'fa':LANG);if(now!==last){last=now;rebuildFilterLabels()}},700);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',rebuildFilterLabels);else rebuildFilterLabels();
})();
