
(function(){
  if(window.__FN_EXACT_AI_FINAL__) return; window.__FN_EXACT_AI_FINAL__=true;
  var S={id:null,type:null,token:0,rich:null,ready:null,answerCache:new Map()};
  function el(id){return document.getElementById(id)}
  function clean(v){return String(v==null?'':v).replace(/\s+/g,' ').trim()}
  function fa(){return typeof LANG!=='undefined'&&LANG==='fa'}
  function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
  function titleFromModal(){return clean((el('d-title')||{}).textContent||'')||clean((el('d-title-secondary')||{}).textContent||'')||'این اثر'}
  function yearFromModal(){return clean((el('d-year')||{}).textContent||'')}
  function clearUI(){if(typeof aiConversation!=='undefined')aiConversation=[];if(typeof aiIsThinking!=='undefined')aiIsThinking=false;['ai-chat-area','ai-fs-chat'].forEach(function(id){var x=el(id);if(x)x.innerHTML='<div class="ai-msg-bot">'+(fa()?'در حال آماده‌سازی دستیار همین اثر…':'Preparing this title assistant…')+'</div>'});['ai-quick-btns','ai-fs-quick-btns'].forEach(function(id){var x=el(id);if(x){x.innerHTML='';x.setAttribute('data-exact-ai','')}})}
  function initExact(r){if(!r||String(r.tmdbId)!==String(S.id))return;S.rich=r;S.answerCache=new Map();aiCurrentTitle=r.originalTitle||r.title;aiCurrentType=r.mediaType;aiRichData=r;aiConversation=[];aiIsThinking=false;var ctx=aiCurrentTitle+(r.year?' ('+r.year+')':'');var lab=el('ai-box-label');if(lab)lab.textContent=fa()?'دستیار AI · «'+ctx+'»':'AI · "'+ctx+'"';var badge=el('ai-context-badge');if(badge){badge.innerHTML='<span style="color:#4285f4;font-weight:700">🎬 '+esc(ctx)+'</span>';badge.style.display='block'}var welcome=fa()?'سلام! این دستیار فقط درباره «'+esc(ctx)+'» پاسخ می‌دهد. هر سؤالی داری بپرس.':'Hi! This assistant is locked to "'+esc(ctx)+'". Ask anything about this exact title.';['ai-chat-area','ai-fs-chat'].forEach(function(id){var x=el(id);if(x)x.innerHTML='<div class="ai-msg-bot">'+welcome+'</div>'});var qs=fa()?['خلاصه داستان بدون اسپویل','نقاط قوت و ضعف چیست؟','بازیگران و شخصیت‌های مهم را تحلیل کن','پایان را با اسپویل توضیح بده','فکت‌های مطمئن درباره اثر','آثار مشابه معرفی کن']:['Summarize it without spoilers','What are its strengths and weaknesses?','Analyze the main cast and characters','Explain the ending with spoilers','Give confirmed facts about it','Recommend similar titles'];var html=qs.map(function(q){return '<div class="ai-quick-btn" data-question="'+esc(q).replace(/'/g,'&#39;')+'" onclick="askQuick(this.dataset.question)">'+esc(q)+'</div>'}).join('');['ai-quick-btns','ai-fs-quick-btns'].forEach(function(id){var x=el(id);if(x){x.innerHTML=html;x.style.display='flex';x.setAttribute('data-exact-ai',String(r.tmdbId)+'|'+r.year)}});['ai-input','ai-fs-input'].forEach(function(id){var x=el(id);if(x)x.placeholder=fa()?'سؤالت را درباره همین اثر بپرس…':'Ask about this exact title…'})}
  async function loadExact(id,type,token){try{var d=await getData(type+'/'+id+'?append_to_response=external_ids'),en=await getDataEN(type+'/'+id+'?append_to_response=external_ids'),cr=await getData(type+'/'+id+'/credits'),kw=await getData(type+'/'+id+'/keywords');if(token!==S.token||String(id)!==String(S.id))return;var base=en&&en.id?en:d||{},local=d||{},people=(cr&&cr.cast||[]).slice(0,12).map(function(x){return x.name}).filter(Boolean).join(', '),dirs=(cr&&cr.crew||[]).filter(function(x){return x.job==='Director'||x.department==='Directing'}).slice(0,5).map(function(x){return x.name}).filter(Boolean).join(', '),keywords=(kw&&(kw.keywords||kw.results)||[]).slice(0,20).map(function(x){return x.name}).filter(Boolean).join(', ');var r={tmdbId:id,mediaType:type,originalTitle:clean(base.title||base.name||local.original_title||local.original_name||titleFromModal()),year:clean(((base.release_date||base.first_air_date||local.release_date||local.first_air_date||'').split('-')[0]))||yearFromModal(),overview:clean(base.overview||local.overview||''),overviewFa:clean(local.overview||''),genres:(local.genres||base.genres||[]).map(function(x){return x.name}).join(', '),cast:people,directors:dirs,rating:base.vote_average||local.vote_average||'',runtime:base.runtime?base.runtime+' min':(base.number_of_seasons?base.number_of_seasons+' seasons':''),countries:(base.production_countries||[]).map(function(x){return x.name}).join(', '),keywords:keywords,imdbId:(base.external_ids&&base.external_ids.imdb_id)||(local.external_ids&&local.external_ids.imdb_id)||''};if(token===S.token)initExact(r)}catch(e){if(token===S.token)initExact({tmdbId:id,mediaType:type,originalTitle:titleFromModal(),year:yearFromModal(),overview:clean((el('d-desc')||{}).textContent||''),overviewFa:clean((el('d-desc')||{}).textContent||''),genres:'',cast:'',directors:'',rating:'',runtime:'',keywords:''})}}
  function installOpen(){var oldOpen=window.openDetail;if(typeof oldOpen!=='function'||oldOpen.__fnExactWrap)return;if(oldOpen===window.__fnExactOriginal)return;var wrapped=async function(id,type){type=type||'movie';if(type==='person_works')return oldOpen.apply(this,arguments);S.id=id;S.type=type;S.token++;S.answerCache=new Map();var t=S.token;clearUI();var out=await oldOpen.apply(this,arguments);if(t===S.token){S.ready=loadExact(id,type,t);S.ready.catch(function(){});}return out};wrapped.__fnExactWrap=true;window.__fnExactOriginal=oldOpen;try{openDetail=wrapped}catch(e){}window.openDetail=wrapped} installOpen();setTimeout(installOpen,0);setTimeout(installOpen,500);setTimeout(installOpen,1500);
  var oldInit=window.initAIBox;window.initAIBox=function(title,type,year,rich){if(S.id!=null&&rich&&rich.tmdbId!=null&&String(rich.tmdbId)!==String(S.id))return;if(S.id!=null&&(!rich||rich.tmdbId==null))return;return oldInit&&oldInit.apply(this,arguments)};
  function facts(){var r=S.rich||{};return ['Exact title: '+r.originalTitle,'Year: '+r.year,'Type: '+(r.mediaType==='tv'?'TV series':'movie'),'TMDB ID: '+r.tmdbId,r.imdbId?'IMDb ID: '+r.imdbId:'','Genres: '+r.genres,'Director(s): '+r.directors,'Main cast: '+r.cast,'Runtime/seasons: '+r.runtime,'Rating: '+r.rating+'/10','Keywords: '+r.keywords,'Official synopsis: '+(r.overview||'not available')].filter(Boolean).join('\n')}
  function local(q){var r=S.rich||{},x=String(q||'').toLowerCase(),t=r.originalTitle||titleFromModal(),ov=fa()?(r.overviewFa||r.overview):r.overview,head=fa()?'درباره «'+esc(t)+'»':'About "'+esc(t)+'"';
    if(/خلاصه|داستان|summary|story|plot/.test(x)){var fallback=fa()?'خلاصهٔ کامل در منبع فعلی نمایش داده نشده، اما می‌توانم این اثر را از روی داده‌های واقعی آن تحلیل کنم. سال: '+(r.year||'نامشخص')+'؛ ژانر: '+(r.genres||'ثبت‌نشده')+'؛ امتیاز: '+(r.rating||'ثبت‌نشده')+'.':'The source does not expose a complete synopsis here, but I can still analyze this title from its verified metadata. Year: '+(r.year||'unknown')+'; genre: '+(r.genres||'not listed')+'; rating: '+(r.rating||'not listed')+'.';return '<strong>'+head+'</strong><br><br>'+esc(ov||fallback)+(r.cast?'<br><br><strong>'+(fa()?'بازیگران:':'Cast:')+'</strong> '+esc(r.cast):'')}
    if(/بازیگر|شخصیت|cast|character/.test(x))return '<strong>'+(fa()?'بازیگران و شخصیت‌ها:':'Cast and characters:')+'</strong><br>'+esc(r.cast||(fa()?'فهرست بازیگران در دادهٔ فعلی کامل نیست؛ امتیاز و ژانر اثر: ':'The cast list is incomplete in the current data; the title metadata is: ')+(r.genres||'not listed')+' · '+(r.rating||'not listed'));
    if(/فکت|fact|trivia/.test(x))return '<strong>'+(fa()?'فکت‌های تأییدشده:':'Confirmed facts:')+'</strong><br>• '+esc(t)+'<br>• '+esc(r.year||'Unknown')+'<br>• '+esc(r.genres||'Unknown')+'<br>• TMDB: '+esc(r.tmdbId);
    return '<strong>'+head+'</strong><br><br>'+esc(ov||(fa()?'دادهٔ قابل استفادهٔ این اثر: سال '+(r.year||'نامشخص')+'، ژانر '+(r.genres||'ثبت‌نشده')+' و امتیاز '+(r.rating||'ثبت‌نشده')+'. بر اساس همین اطلاعات، می‌توانم دربارهٔ حال‌وهوا، ارزش تماشا و آثار مشابه راهنمایی بدهم.':'Useful available metadata for this title: year '+(r.year||'unknown')+', genre '+(r.genres||'not listed')+', rating '+(r.rating||'not listed')+'. I can use this to discuss its tone, viewing value, and similar titles.'))}
  async function exactAsk(q){q=clean(q);if(!q)return fa()?'لطفاً سؤالت را بنویس.':'Please type a question.';if(S.ready){try{await Promise.race([S.ready,new Promise(function(resolve){setTimeout(resolve,9000)})])}catch(e){}}if(!S.id)return local(q);var key=String(S.id)+'|'+(fa()?'fa':'en')+'|'+q.toLowerCase();if(S.answerCache.has(key))return S.answerCache.get(key);var r=S.rich||{tmdbId:S.id,mediaType:S.type,originalTitle:titleFromModal(),year:yearFromModal(),overview:clean((el('d-desc')||{}).textContent||'')};var sys=(fa()?'تو دستیار تخصصی سینما هستی. به هر سؤال کاربر پاسخ بده و هیچ‌وقت بی‌پاسخ نگذار. فقط درباره همین اثر دقیق صحبت کن. پاسخ کاملاً فارسی، مفید و روشن باشد. از اطلاعات رسمی زیر استفاده کن؛ اگر جزئیات قطعی نیست صادقانه بگو و هرگز داستان یا فکت نساز. برای سؤال نامرتبط هم کوتاه پاسخ بده و ارتباطش را با این اثر توضیح بده.':'You are a specialized cinema assistant. Always provide a useful answer; never leave the user without a reply. Discuss only this exact title. Answer in clear English using the verified data below. If a detail is unavailable, say so instead of inventing it; for unrelated questions, briefly answer and explain the connection to this title.')+'\n\n'+facts()+'\n\nUser question: '+q;try{var out=await _aiGenerateText(sys,{model:'openai-large',maxTokens:1100,temperature:.2,timeout:26000});out=clean(out);if(out&&out.length>8&&(!fa()||/[\u0600-\u06FF]/.test(out))&&(fa()||!/[\u0600-\u06FF]/.test(out))){S.answerCache.set(key,out);return out}}catch(e){}var ans=local(q);if(!ans||clean(ans).length<8)ans=fa()?'برای «'+esc(r.originalTitle||titleFromModal())+'» اطلاعات رسمی بیشتری برای این سؤال در دسترس نیست، اما سؤال بی‌پاسخ نمی‌ماند: می‌توانم خلاصه، بازیگران، ژانر، امتیاز، نقد یا آثار مشابه این اثر را بررسی کنم.':'I could not retrieve a verified detail for this question about «'+esc(r.originalTitle||titleFromModal())+'», but I can still give a useful title-specific answer from the available metadata: year '+esc(r.year||'unknown')+', genre '+esc(r.genres||'not listed')+', rating '+esc(r.rating||'not listed')+'. Ask me about its plot, cast, tone, rating, or similar titles.';S.answerCache.set(key,ans);return ans}
  window.processAI=processAI=async function(q){if(aiIsThinking)return;aiIsThinking=true;var b1=el('ai-send-btn'),b2=el('ai-fs-send-btn');if(b1)b1.disabled=true;if(b2)b2.disabled=true;addMsgToUI('user',q);showThinking();var ans=await exactAsk(q);removeThinking();if(typeof aiConversation!=='undefined'){aiConversation.push({role:'user',content:q},{role:'assistant',content:ans});if(aiConversation.length>12)aiConversation=aiConversation.slice(-12)}addMsgToUI('bot',ans);aiIsThinking=false;if(b1)b1.disabled=false;if(b2)b2.disabled=false};window.askQuick=askQuick=async function(q){if(!aiIsThinking)await processAI(q)};
})();
