
/* External archive loader: only the index, then the relevant archive part on demand. */
(function () {
  'use strict';
  var FN_DL_BASE='download-data/', fnDlIndex=null, fnDlIndexPromise=null, fnDlParts={};
  function esc(v){var d=document.createElement('div');d.textContent=String(v||'');return d.innerHTML;}
  function isFa(){return typeof LANG==='undefined'||LANG==='fa';}
  function T(a,b){return isFa()?a:b;}
  var fnCurrentImdb='',fnImdbCache={},fnDetailToken=0;
  function selectedImdb(){return fnCurrentImdb;}
  function syncLocale(){
    var page=document.getElementById('fn-download-page'), back=document.getElementById('fn-dl-back'), sub=document.getElementById('fn-dl-page-subtitle'), b=document.getElementById('fn-detail-download-button');
    if(page){page.style.direction=isFa()?'rtl':'ltr';page.dir=isFa()?'rtl':'ltr';}
    if(back){back.setAttribute('aria-label',T('بازگشت','Back'));back.innerHTML='<i class="fa-solid '+(isFa()?'fa-arrow-right':'fa-arrow-left')+'"></i>';}
    if(sub)sub.textContent=T('انتخاب کیفیت دانلود','Choose download quality');
    if(b){var label=b.querySelector('.fn-dl-label');if(label)label.textContent=T('دانلود','Download');}
  }
  function resolveImdb(tmdbId,type){
    if(!tmdbId||(type!=='movie'&&type!=='tv'))return Promise.resolve('');var key=type+':'+tmdbId;if(fnImdbCache[key])return Promise.resolve(fnImdbCache[key]);
    var m=document.documentElement.innerHTML.match(/const\s+API\s*=\s*['\"]([^'\"]+)['\"]/);if(!m)return Promise.resolve('');
    return fetch('https://api.themoviedb.org/3/'+type+'/'+encodeURIComponent(tmdbId)+'/external_ids?api_key='+encodeURIComponent(m[1])).then(function(r){return r.ok?r.json():{};}).then(function(d){var x=(d&&d.imdb_id||'').toLowerCase();fnImdbCache[key]=/^tt\d+$/.test(x)?x:'';return fnImdbCache[key];}).catch(function(){return '';});
  }
  function getIndex(){if(fnDlIndex)return Promise.resolve(fnDlIndex);if(!fnDlIndexPromise)fnDlIndexPromise=fetch(FN_DL_BASE+'download-index.json',{cache:'force-cache'}).then(function(r){if(!r.ok)throw Error('index');return r.json();}).then(function(x){fnDlIndex=x||{};return fnDlIndex;});return fnDlIndexPromise;}
  function loadPart(part){if(fnDlParts[part])return Promise.resolve(fnDlParts[part]);var n=Number(part);if(n!==1&&n!==2&&n!==3)return Promise.reject(Error('archive part'));var file='archive-part-'+n+'.html';return fetch(FN_DL_BASE+file,{cache:'force-cache'}).then(function(r){if(!r.ok)throw Error('archive');return r.text();}).then(function(t){var d=new DOMParser().parseFromString(t,'text/html');fnDlParts[n]=d;return d;});}
  function recordFromArchive(doc,imdb){
    var code=Array.prototype.find.call(doc.querySelectorAll('p'),function(p){var x=(p.textContent||'').toLowerCase();return x.indexOf('imdb code:')>-1&&x.indexOf(imdb)>-1;});if(!code)return null;
    var head=code.previousElementSibling;while(head&&head.tagName!=='H3')head=head.previousElementSibling;var title=head?head.textContent.replace(/^\s*\d+\.\s*/,'').replace(/\s+start_year\s*$/i,'').trim():'',cat='',season='',groups={softsub:[],dubbed:[]},n=code.nextElementSibling;
    while(n&&n.tagName!=='H3'){var txt=(n.textContent||'').trim(),low=txt.toLowerCase();if(/soft\s*sub/.test(low))cat='softsub';else if(/dubbed/.test(low))cat='dubbed';else if(/^season\s*\d+/i.test(txt))season=txt.match(/\d+/)[0];else if(cat&&n.querySelectorAll('a').length)Array.prototype.forEach.call(n.querySelectorAll('a'),function(a){var q=(a.textContent||'').trim(),href=a.getAttribute('href')||'';if(!href||!q)return;var tail=txt.replace(q,'').replace(/^\s*\/\s*/,'').trim(),size=(tail.match(/(?:\d+(?:\.\d+)?\s*(?:GB|MB))/i)||[])[0]||'';groups[cat].push({quality:q,url:href,size:size,season:season});});n=n.nextElementSibling;}
    return {title:title,groups:groups};
  }
  function menuHtml(url,tone){var u=esc(url);return '<div class="fn-dl-methods" aria-hidden="true">'
    +'<button type="button" class="fn-dl-method" data-fn-action="copy" data-url="'+u+'"><i class="fa-regular fa-copy"></i><span>'+T('کپی لینک','Copy link')+'</span></button>'
    +'<button type="button" class="fn-dl-method" data-fn-action="adm" data-url="'+u+'"><i class="fa-solid fa-mobile-screen-button"></i><span>'+T('دانلود با ADM (اندروید)','Download with ADM (Android)')+'</span></button>'
    +'<button type="button" class="fn-dl-method fn-dl-method-primary" data-fn-action="download" data-url="'+u+'"><i class="fa-solid fa-download"></i><span>'+T('دانلود','Download')+'</span></button>'
    +'<button type="button" class="fn-dl-method fn-dl-more-toggle" data-fn-action="more"><i class="fa-solid fa-ellipsis"></i><span>'+T('بیشتر…','More…')+'</span><i class="fa-solid fa-chevron-down fn-dl-chevron"></i></button>'
    +'<div class="fn-dl-more-options">'
      +'<button type="button" class="fn-dl-method" data-fn-action="ios" data-url="'+u+'"><i class="fa-brands fa-apple"></i><span>'+T('باز کردن با IDM (iOS)','Open with IDM (iOS)')+'</span></button>'
      +'<button type="button" class="fn-dl-method" data-fn-action="desktop" data-url="'+u+'"><i class="fa-solid fa-desktop"></i><span>'+T('دانلود با دانلود منیجر (دسکتاپ)','Download with download manager (Desktop)')+'</span></button>'
      +'<button type="button" class="fn-dl-method" data-fn-action="share" data-url="'+u+'"><i class="fa-solid fa-share-nodes"></i><span>'+T('انتخاب برنامهٔ دیگر…','Choose another app…')+'</span></button>'
    +'</div></div>';}
  function groupHtml(label,icon,tone,links){if(!links.length)return '';var map={};links.forEach(function(x){(map[x.season||(isFa()?'فیلم':'Movie')]||(map[x.season||(isFa()?'فیلم':'Movie')]=[])).push(x);});var out='<section style="margin:0 0 20px;border:1px solid '+tone+';border-radius:15px;overflow:hidden;background:#101512;"><div style="padding:12px 14px;background:rgba(255,255,255,.035);font-weight:800;color:'+tone+';"><i class="fa-solid '+icon+'"></i> '+label+'</div>';
    Object.keys(map).forEach(function(s){out+='<div style="padding:12px 12px 2px;">'+((s===(isFa()?'فیلم':'Movie'))?'':'<div style="font-size:12px;color:var(--text);font-weight:bold;margin:0 2px 9px;">'+T('فصل ','Season ')+esc(s)+'</div>');map[s].forEach(function(x){var u=esc(x.url),playMenu='<div class="fn-dl-play-options"><div class="fn-dl-play-note">'+T('در اندروید، در صورت نصب‌بودن برنامه، تلاش می‌شود لینک مستقیماً در پلیر باز شود. در iOS و دسکتاپ، گزینهٔ اشتراک‌گذاری یا کپی لینک را انتخاب کنید.','On Android, the link is opened in the selected installed player when possible. On iOS and desktop, use sharing or copy the link to your player.')+'</div><button type="button" class="fn-dl-method" data-fn-action="vlc" data-url="'+u+'"><i class="fa-solid fa-play"></i><span>'+T('پخش با VLC','Play with VLC')+'</span></button><button type="button" class="fn-dl-method" data-fn-action="mx" data-url="'+u+'"><i class="fa-solid fa-play"></i><span>'+T('پخش با MX Player','Play with MX Player')+'</span></button><button type="button" class="fn-dl-method" data-fn-action="km" data-url="'+u+'"><i class="fa-solid fa-play"></i><span>'+T('پخش با KMPlayer','Play with KMPlayer')+'</span></button><button type="button" class="fn-dl-method" data-fn-action="player-share" data-url="'+u+'"><i class="fa-solid fa-share-nodes"></i><span>'+T('باز کردن با پلیر دیگر…','Open with another player…')+'</span></button></div>';out+='<div class="fn-dl-choice"><div class="fn-dl-quality" style="--fn-tone:'+tone+';"><button type="button" class="fn-dl-quality-main" data-url="'+u+'" aria-expanded="false"><i class="fa-solid fa-download" style="color:'+tone+';"></i><span style="flex:1;min-width:0;direction:ltr;text-align:left;font-size:12px;font-weight:700;">'+esc(x.quality)+'</span>'+(x.size?'<span style="font-size:11px;color:var(--sub);direction:ltr;">'+esc(x.size)+'</span>':'')+'<i class="fa-solid fa-chevron-down fn-dl-chevron"></i></button><button type="button" class="fn-dl-play-trigger" data-fn-action="play-menu" aria-label="'+T('گزینه‌های پخش','Playback options')+'" title="'+T('گزینه‌های پخش','Playback options')+'"><i class="fa-solid fa-play"></i></button></div>'+menuHtml(x.url,tone)+playMenu+'</div>';});out+='</div>';});return out+'</section>';}
  function notice(msg,ok){var n=document.getElementById('fn-dl-notice');if(!n){n=document.createElement('div');n.id='fn-dl-notice';document.body.appendChild(n);}n.textContent=msg;n.className='show '+(ok?'ok':'');clearTimeout(notice.timer);notice.timer=setTimeout(function(){n.className='';},2400);}
  function directDownload(url){var a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.download='';document.body.appendChild(a);a.click();a.remove();}
  function copyUrl(url){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(url).then(function(){notice(T('لینک کپی شد','Link copied'),true);},function(){fallbackCopy(url);});}else fallbackCopy(url);}
  function fallbackCopy(url){var t=document.createElement('textarea');t.value=url;t.style.cssText='position:fixed;opacity:0;';document.body.appendChild(t);t.select();try{document.execCommand('copy');notice(T('لینک کپی شد','Link copied'),true);}catch(e){notice(T('کپی لینک ممکن نشد','Could not copy the link'));}t.remove();}
  function shareUrl(url){if(navigator.share){navigator.share({url:url}).catch(function(){});}else{copyUrl(url);notice(T('لینک کپی شد؛ آن را در برنامهٔ دلخواه باز کنید','Link copied; open it in your preferred app'),true);}}
  function openADM(url){if(!/Android/i.test(navigator.userAgent)){notice(T('ADM برای اندروید است؛ دانلود مستقیم آغاز می‌شود','ADM is for Android; starting direct download'));directDownload(url);return;}var m=url.match(/^(https?):\/\/(.*)$/i);if(!m){directDownload(url);return;}var intent='intent://'+m[2]+'#Intent;scheme='+m[1]+';package=com.dv.adm;end';window.location.href=intent;setTimeout(function(){directDownload(url);},850);}
  function openPlayer(url,pkg,name){if(/Android/i.test(navigator.userAgent)){var m=url.match(/^(https?):\/\/(.*)$/i);if(!m){shareUrl(url);return;}var moved=false,onHide=function(){moved=document.hidden;};document.addEventListener('visibilitychange',onHide);window.location.href='intent://'+m[2]+'#Intent;scheme='+m[1]+';package='+pkg+';end';setTimeout(function(){document.removeEventListener('visibilitychange',onHide);if(!moved){notice(T(name+' نصب نیست یا این لینک را باز نمی‌کند؛ انتخاب پلیر دیگر نمایش داده شد.',name+' is unavailable or cannot open this link; choose another player.'),false);shareUrl(url);}},1100);return;}if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){notice(T('از منوی اشتراک‌گذاری، پلیر نصب‌شده را انتخاب کنید.','Choose an installed player from the share menu.'),true);shareUrl(url);return;}copyUrl(url);notice(T('لینک کپی شد؛ آن را در '+name+' باز کنید.','Link copied; open it in '+name+'.'),true);}
  function bindDownloadMethods(){var box=document.getElementById('fn-dl-page-content');if(!box||box.dataset.fnBound)return;box.dataset.fnBound='1';box.addEventListener('click',function(e){var q=e.target.closest('.fn-dl-quality-main');if(q){var choice=q.closest('.fn-dl-choice'),open=choice.classList.contains('open');Array.prototype.forEach.call(box.querySelectorAll('.fn-dl-choice.open'),function(x){x.classList.remove('open');x.querySelector('.fn-dl-quality-main').setAttribute('aria-expanded','false');});if(!open){choice.classList.add('open');q.setAttribute('aria-expanded','true');}return;}var b=e.target.closest('[data-fn-action]');if(!b)return;e.stopPropagation();var action=b.getAttribute('data-fn-action'),url=b.getAttribute('data-url')||'',choice=b.closest('.fn-dl-choice');if(action==='more'){choice.classList.toggle('more-open');return;}if(action==='play-menu'){choice.classList.toggle('play-open');return;}if(action==='copy')copyUrl(url);else if(action==='adm')openADM(url);else if(action==='download'||action==='desktop')directDownload(url);else if(action==='ios'||action==='share'||action==='player-share')shareUrl(url);else if(action==='vlc')openPlayer(url,'org.videolan.vlc','VLC');else if(action==='mx')openPlayer(url,'com.mxtech.videoplayer.ad','MX Player');else if(action==='km')openPlayer(url,'com.kmplayer','KMPlayer');});}
  window.closeFNDownloadPage=function(){var p=document.getElementById('fn-download-page');if(p){p.style.display='none';p.setAttribute('aria-hidden','true');}};
  function openInternalFallback(){
    var page=document.getElementById('fn-download-page'); if(page){page.style.display='none';page.setAttribute('aria-hidden','true');}
    if(typeof renderDlButtons==='function') renderDlButtons(curTitle||'');
    var box=document.getElementById('download-links-box');
    if(box){box.style.display='block';box.scrollIntoView({behavior:'smooth',block:'center'});}
  }
  window.openFNDownloadPage=async function(){syncLocale();var page=document.getElementById('fn-download-page'),box=document.getElementById('fn-dl-page-content'),title=document.getElementById('fn-dl-page-title'),imdb=selectedImdb(),token=fnDetailToken;if(!imdb)return;title.textContent=(document.getElementById('d-title')||{}).textContent||'';box.innerHTML='<div style="text-align:center;padding:50px 15px;color:var(--sub);"><i class="fa-solid fa-spinner fa-spin" style="font-size:25px;color:var(--primary);"></i><div style="margin-top:12px;">'+T('در حال آماده‌سازی لینک‌ها…','Preparing download links…')+'</div></div>';page.style.display='block';page.setAttribute('aria-hidden','false');try{var index=await getIndex(),part=index[imdb];if(token!==fnDetailToken||imdb!==selectedImdb())return;if(!part){openInternalFallback();return;}var rec=recordFromArchive(await loadPart(part),imdb);if(token!==fnDetailToken||imdb!==selectedImdb())return;if(!rec||(!rec.groups.softsub.length&&!rec.groups.dubbed.length))throw Error('record');box.innerHTML='<div style="font-size:12px;color:var(--sub);line-height:1.8;margin-bottom:15px;">'+T('کیفیت، انکود و حجمِ موجود را انتخاب کنید.','Choose from the available quality, encode and file size.')+'</div>'+groupHtml(T('زیرنویس فارسی چسبیده','Persian hardcoded subtitles'),'fa-closed-captioning','var(--primary)',rec.groups.softsub)+groupHtml(T('دوبله فارسی','Persian dubbed'),'fa-microphone-lines','var(--primary)',rec.groups.dubbed);}catch(e){if(token!==fnDetailToken||imdb!==selectedImdb())return;if(typeof DOWNLOADS_DB!=='undefined'&&DOWNLOADS_DB[imdb]){openInternalFallback();return;}box.innerHTML='<div style="text-align:center;padding:45px 12px;color:var(--sub);line-height:2;">'+T('لینک دانلودی برای این اثر پیدا نشد یا فایل آرشیو در دسترس نیست.','No download links were found for this title, or the archive is unavailable.')+'</div>';}};
  function setDownloadButtonPending(){var b=document.getElementById('fn-detail-download-button');if(!b)return;b.style.display='flex';b.style.opacity='.55';b.style.pointerEvents='none';b.setAttribute('aria-disabled','true');syncLocale();}
  function updateButton(token){if(token!==fnDetailToken)return;var b=document.getElementById('fn-detail-download-button'),imdb=selectedImdb();if(!b)return;var db=(!imdb||typeof DOWNLOADS_DB==='undefined')?null:DOWNLOADS_DB[imdb],dbAvailable=!!(db&&((db.type==='tvSeries')||(db.softsub&&Object.keys(db.softsub).length)||(db.dubbed&&Object.keys(db.dubbed).length)));var available=!!(imdb&&((fnDlIndex&&fnDlIndex[imdb])||dbAvailable));b.style.display=available?'flex':'none';b.style.opacity='';b.style.pointerEvents=available?'':'none';b.setAttribute('aria-disabled',available?'false':'true');syncLocale();}
  function addButton(){
    var playLabel=document.getElementById('txt-hero-play'),b=document.getElementById('fn-detail-download-button');
    if(b){syncLocale();return;} if(!playLabel)return;
    var play=playLabel.parentElement, holder=play.parentElement;
    var group=document.createElement('div'); group.className='fn-play-download-group';
    holder.insertBefore(group,play); group.appendChild(play);
    b=document.createElement('div'); b.id='fn-detail-download-button'; b.setAttribute('role','button'); b.tabIndex=0;
    b.onclick=window.openFNDownloadPage;
    b.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();window.openFNDownloadPage();}};
    b.innerHTML='<div class="hero-play-circle fn-download-circle"><i class="fa-solid fa-download"></i></div><span class="fn-dl-label"></span>';
    group.appendChild(b); syncLocale();
  }
  bindDownloadMethods();
  var originalOpen=window.openDetail;if(typeof originalOpen==='function')window.openDetail=async function(){var tmdbId=arguments[0],mediaType=arguments[1],token=++fnDetailToken;fnCurrentImdb='';var r=originalOpen.apply(this,arguments);try{await r;}finally{if(token===fnDetailToken){addButton();setDownloadButtonPending();Promise.all([resolveImdb(tmdbId,mediaType),getIndex()]).then(function(result){if(token!==fnDetailToken)return;fnCurrentImdb=result[0];updateButton(token);setTimeout(function(){if(token===fnDetailToken)updateButton(token);},350);}).catch(function(){if(token!==fnDetailToken)return;var b=document.getElementById('fn-detail-download-button'),db=(typeof DOWNLOADS_DB!=='undefined'&&fnCurrentImdb&&DOWNLOADS_DB[fnCurrentImdb]),ok=!!(db&&((db.type==='tvSeries')||(db.softsub&&Object.keys(db.softsub).length)||(db.dubbed&&Object.keys(db.dubbed).length)));if(b){b.style.display=ok?'flex':'none';b.style.opacity='';b.style.pointerEvents=ok?'':'none';b.setAttribute('aria-disabled',ok?'false':'true');syncLocale();}});}}return r;};document.addEventListener('DOMContentLoaded',function(){addButton();syncLocale();bindDownloadMethods();});
})();
