
(function(){'use strict';
  var TTL=6*60*60*1000,sourceKey='fn_live_epg_data_cache_v2',channelKey='fn_live_epg_channel_cache_v2',active=null,requestNo=0;
  var defaultEndpoints=['https://iptv-org.github.io/epg/guides/us.xml.gz','https://iptv-org.github.io/epg/guides/ir.xml.gz'];
  function fa(){return typeof LANG==='undefined'||LANG==='fa'}
  function tr(a,b){return fa()?a:b}
  function esc(x){var d=document.createElement('div');d.textContent=String(x==null?'':x);return d.innerHTML}
  function norm(x){return String(x==null?'':x).toLocaleLowerCase().normalize('NFKD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^\\p{L}\\p{N}]+/gu,' ').trim().replace(/\\s+/g,' ')}
  function exactId(x){return String(x==null?'':x).trim().toLocaleLowerCase()}
  function read(key,fallback){try{var x=JSON.parse(localStorage.getItem(key)||'null');return x&&typeof x==='object'?x:fallback}catch(e){return fallback}}
  function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(e){return false}}
  function endpoints(channel){var x=window.FN_LIVE_EPG_ENDPOINTS;if(!Array.isArray(x)){var saved=read('fn_live_epg_endpoints_v1',null);x=Array.isArray(saved)?saved:defaultEndpoints.slice()}else{x=x.slice()}var country=String(channel&&channel.country||'').trim().toLowerCase();if(country&&/^[a-z]{2}$/.test(country)){x.push('https://iptv-org.github.io/epg/guides/'+country+'.xml.gz');x.push('https://iptv-epg.org/files/epg-'+country+'.xml.gz')}x.push('https://iptv-org.github.io/epg/guides/ir.xml.gz');var seen={};return x.map(function(v){return String(v||'').trim()}).filter(function(v){if(!v||seen[v])return false;seen[v]=1;return true}).slice(0,6)}
  function status(text){var e=document.getElementById('fn-live-epg-status');if(e){e.textContent=text;e.style.display=text?'':'none'}}
  function setSummary(x){var e=document.getElementById('fn-live-epg-channel');if(e)e.textContent=x&&x.name?' · '+x.name:''}
  function cacheChannelId(x){return x&&x.id?'id:'+exactId(x.id):'name:'+norm(x&&x.name)}
  function xmlText(el,tag){var n=el&&el.getElementsByTagName(tag)[0];return n?String(n.textContent||'').trim():''}
  function parseDate(raw){var s=String(raw||'').trim(),m=s.match(/^(\\d{4})(\\d{2})(\\d{2})(\\d{2})(\\d{2})(\\d{2})(?:\\s*([+-])(\\d{2})(?::?(\\d{2}))?)?/);if(m){var base=Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6]),off=m[7]?((+m[8]*60+(+m[9]||0))*60000)*(m[7]==='+'?1:-1):0;return new Date(base-off)}var d=new Date(s);return isNaN(d.getTime())?null:d}
  function parseFeed(text,x){var doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw Error('Invalid XMLTV');var wantedId=exactId(x&&x.id),wantedName=norm(x&&x.name),ids=[],channels=doc.getElementsByTagName('channel');for(var i=0;i<channels.length;i++){var c=channels[i],cid=exactId(c.getAttribute('id')||'');if(wantedId&&cid===wantedId)ids.push(cid)}var matchedBy=wantedId&&ids.length?'tvg-id':'';if(!ids.length&&wantedName){for(var j=0;j<channels.length;j++){var cc=channels[j],names=cc.getElementsByTagName('display-name'),ok=false;for(var k=0;k<names.length;k++){if(norm(names[k].textContent)===wantedName){ok=true;break}}if(ok)ids.push(exactId(cc.getAttribute('id')||''))}if(ids.length)matchedBy='name'}if(!ids.length&&wantedId){for(var q=0;q<channels.length;q++){var qc=channels[q],qid=exactId(qc.getAttribute('id')||'');if(qid===wantedId)ids.push(qid)}if(ids.length)matchedBy='tvg-id'}var idSet={};ids.forEach(function(id){if(id)idSet[id]=1});var programmes=doc.getElementsByTagName('programme'),out=[];for(var z=0;z<programmes.length;z++){var p=programmes[z],pid=exactId(p.getAttribute('channel')||'');if(!idSet[pid])continue;var start=parseDate(p.getAttribute('start')),end=parseDate(p.getAttribute('stop'));if(!start||!end||end<=start)continue;var title=xmlText(p,'title');if(!title)continue;out.push({start:start.getTime(),end:end.getTime(),title:title,desc:xmlText(p,'desc')})}out.sort(function(a,b){return a.start-b.start});var now=Date.now(),windowed=out.filter(function(p){return p.end>=now-36*60*60*1000&&p.start<=now+7*24*60*60*1000});return {matched:!!matchedBy&&windowed.length>0,matchedBy:matchedBy,programmes:windowed.slice(0,240)} }
  async function fetchText(url){var r=await fetch(url,{cache:'no-store',mode:'cors'});if(!r.ok)throw Error('EPG HTTP '+r.status);var isGz=/\\.gz(?:$|[?#])/i.test(url)||(r.headers.get('content-type')||'').toLowerCase().indexOf('gzip')>-1;if(isGz&&window.DecompressionStream){var stream=new Blob([await r.arrayBuffer()]).stream().pipeThrough(new DecompressionStream('gzip'));return await new Response(stream).text()}return await r.text()}
  function fresh(x){return x&&Number(x.at)>0&&Date.now()-Number(x.at)<TTL}
  function choose(programmes,now){var p=(programmes||[]).filter(function(x){return x&&isFinite(x.start)&&isFinite(x.end)&&x.end>x.start}).sort(function(a,b){return a.start-b.start}),current=null,previous=null,next=null;for(var i=0;i<p.length;i++){if(p[i].start<=now&&p[i].end>now)current=p[i];else if(p[i].end<=now)previous=p[i];else if(!next&&p[i].start>now)next=p[i]}return {previous:previous,current:current,next:next}}
  function fmt(t){try{return new Intl.DateTimeFormat(fa()?'fa-IR':'en-US',{hour:'2-digit',minute:'2-digit'}).format(new Date(t))}catch(e){return new Date(t).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}}
  function render(programmes,matched){var d=document.getElementById('fn-live-epg');if(d){d.hidden=!matched;if(!matched)d.open=false;}var list=document.getElementById('fn-live-epg-list');if(!list)return;list.innerHTML='';if(!matched||!programmes||!programmes.length){list.innerHTML='<div class="fn-live-epg-empty">'+esc(tr('اطلاعات برنامه موجود نیست','EPG not available'))+'</div>';return}var s=choose(programmes,Date.now()),rows=[['previous',tr('قبلی','Previous'),s.previous],['current',tr('اکنون','Now'),s.current],['next',tr('بعدی','Next'),s.next]];rows.forEach(function(row){var el=document.createElement('div');el.className='fn-live-epg-item'+(row[0]==='current'&&row[2]?' current':'');if(row[2]){var p=row[2];el.innerHTML='<div><div class="fn-live-epg-kind">'+esc(row[1])+'</div><div class="fn-live-epg-time">'+esc(fmt(p.start))+' – '+esc(fmt(p.end))+'</div></div><div><div class="fn-live-epg-name">'+esc(p.title)+'</div>'+(p.desc?'<div class="fn-live-epg-desc">'+esc(p.desc)+'</div>':'')+'</div>'}else{el.innerHTML='<div class="fn-live-epg-kind">'+esc(row[1])+'</div><div class="fn-live-epg-empty">—</div>'}list.appendChild(el)})}
  function drawLanguage(){var title=document.querySelector('[data-live-epg-label="title"]');if(title)title.textContent=tr('راهنمای برنامه','Programme guide');var d=document.getElementById('fn-live-epg');if(d&&d.open&&active)render(active.programmes,active.matched)}
  async function load(x){if(!x)return;active={channel:x,programmes:[],matched:false};var d=document.getElementById('fn-live-epg');if(d){d.hidden=true;d.open=false}setSummary(x);var serial=++requestNo;status(tr('در حال دریافت راهنمای برنامه…','Loading programme guide…'));var ck=cacheChannelId(x),cc=read(channelKey,{}),cached=cc[ck];if(fresh(cached)){active.programmes=cached.programmes||[];active.matched=!!cached.matched;render(active.programmes,active.matched);status(active.matched?tr('راهنما از حافظه بارگذاری شد','Guide loaded from cache'):tr('اطلاعات برنامه موجود نیست','EPG not available'));return}var sc=read(sourceKey,{}),eps=endpoints(x);for(var i=0;i<eps.length;i++){if(serial!==requestNo)return;var ep=eps[i],bucket=sc[ep];if(fresh(bucket)&&bucket.channels&&Object.prototype.hasOwnProperty.call(bucket.channels,ck)){var saved=bucket.channels[ck];active.programmes=saved.programmes||[];active.matched=!!saved.matched;if(active.matched)break;continue}try{var parsed=parseFeed(await fetchText(ep),x);bucket=fresh(bucket)&&bucket.channels?bucket:{at:Date.now(),channels:{}};bucket.at=Date.now();bucket.channels[ck]=parsed;sc[ep]=bucket;write(sourceKey,sc);active.programmes=parsed.programmes||[];active.matched=!!parsed.matched;if(active.matched)break}catch(e){if(i===eps.length-1)active.matched=false}}if(serial!==requestNo)return;cc[ck]={at:Date.now(),matched:active.matched,programmes:active.programmes||[]};write(channelKey,cc);render(active.programmes,active.matched);status(active.matched?tr('راهنما به‌روز شد','Guide updated'):tr('اطلاعات برنامه موجود نیست','EPG not available'))}
  window.fnLiveEPGLoad=function(x){load(x)};
  function init(){var d=document.getElementById('fn-live-epg');if(!d)return;d.addEventListener('toggle',function(){if(d.open){if(active)load(active.channel);else status(tr('یک شبکه را برای دریافت راهنمای برنامه پخش کنید','Play a channel to load its programme guide'))}});drawLanguage();var last='';setInterval(function(){var lang=String(typeof LANG==='undefined'?'fa':LANG);if(lang!==last){last=lang;drawLanguage()}if(d.open&&active&&active.matched)render(active.programmes,active.matched)},60000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
