
(function(){'use strict';
 var KEY='fn_live_view_mode_v1', modes=['title','compact','list'], mode='title';
 try{var saved=localStorage.getItem(KEY);if(modes.indexOf(saved)>-1)mode=saved}catch(e){}
 function fa(){return typeof LANG==='undefined'||LANG==='fa'}
 function tx(a,b){return fa()?a:b}
 function esc(x){var d=document.createElement('div');d.textContent=String(x==null?'':x);return d.innerHTML}
 function labels(){return [{k:'title',fa:'نمایش عنوانی',en:'Title view',i:'fa-table-cells-large'},{k:'compact',fa:'نمایش فشرده',en:'Compact view',i:'fa-table-list'},{k:'list',fa:'گرید',en:'Grid',i:'fa-table-cells'}]}
 function applyMode(){var g=document.getElementById('fn-live-grid');if(!g)return;g.classList.remove('fn-live-view-title','fn-live-view-compact','fn-live-view-list');g.classList.add('fn-live-view-'+mode);var p=document.getElementById('fn-live-view-picker');if(p)p.querySelectorAll('button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-mode')===mode);b.setAttribute('aria-pressed',b.getAttribute('data-mode')===mode?'true':'false')});var b=document.getElementById('fn-live-view-btn');if(b){var x=labels().find(function(v){return v.k===mode})||labels()[0];b.title=tx(x.fa,x.en);b.setAttribute('aria-label',b.title);var i=b.querySelector('i');if(i)i.className='fa-solid '+x.i}}
 window.fnLiveSetViewMode=function(m){if(modes.indexOf(m)<0)return;mode=m;try{localStorage.setItem(KEY,mode)}catch(e){}applyMode();var p=document.getElementById('fn-live-view-picker');if(p)p.classList.remove('open')};
 function ensure(){var a=document.querySelector('#live-tab .fn-live-top-actions');if(!a)return;var reset=a.querySelector('button[onclick*="fnLiveResetFilters"]');if(!reset)return;if(!document.getElementById('fn-live-view-control')){var w=document.createElement('span');w.id='fn-live-view-control';w.className='fn-live-view-wrap';w.innerHTML='<button id="fn-live-view-btn" type="button" class="fn-live-icon-btn fn-live-view-btn" onclick="fnLiveToggleViewPicker(event)" title="'+tx('تغییر ظاهر شبکه‌ها','Change channel view')+'" aria-label="'+tx('تغییر ظاهر شبکه‌ها','Change channel view')+'"><i class="fa-solid fa-table-cells-large"></i></button><span id="fn-live-view-picker" class="fn-live-view-picker" role="menu">'+labels().map(function(x){return '<button type="button" role="menuitem" data-mode="'+x.k+'" onclick="fnLiveSetViewMode(\''+x.k+'\')"><i class="fa-solid '+x.i+'"></i> '+esc(tx(x.fa,x.en))+'</button>'}).join('')+'</span>';reset.parentNode.insertBefore(w,reset)}applyMode()}
 window.fnLiveToggleViewPicker=function(e){if(e)e.stopPropagation();ensure();var p=document.getElementById('fn-live-view-picker');if(p)p.classList.toggle('open')};
 document.addEventListener('click',function(e){var w=document.getElementById('fn-live-view-control');if(w&&!w.contains(e.target)){var p=document.getElementById('fn-live-view-picker');if(p)p.classList.remove('open')}});
 var mo=new MutationObserver(function(){ensure();applyMode()});document.addEventListener('DOMContentLoaded',function(){ensure();applyMode();mo.observe(document.body,{childList:true,subtree:true})});if(document.readyState!=='loading'){ensure();applyMode();mo.observe(document.body,{childList:true,subtree:true})}
 setInterval(function(){ensure();applyMode()},900);
 // The app fullscreen button must never request or retain landscape orientation.
 window.fnLiveAppFullscreen=function(){var root=document.documentElement;try{if(document.fullscreenElement||document.webkitFullscreenElement){var ex=document.exitFullscreen||document.webkitExitFullscreen;if(ex)Promise.resolve(ex.call(document)).finally(function(){try{if(screen.orientation&&screen.orientation.unlock)screen.orientation.unlock()}catch(e){}});return}var req=root.requestFullscreen||root.webkitRequestFullscreen;if(req)Promise.resolve(req.call(root,{navigationUI:'hide'})).then(function(){try{if(screen.orientation&&screen.orientation.unlock)screen.orientation.unlock()}catch(e){}}).catch(function(){})}catch(e){}}
 document.addEventListener('fullscreenchange',function(){if(document.fullscreenElement===document.documentElement){try{if(screen.orientation&&screen.orientation.unlock)screen.orientation.unlock()}catch(e){}}});
})();
